"""LS-DYNA keyword descriptions used for documentation generation."""

def get_keyword_description(keyword):
    """Returns a human-readable description for LS-DYNA keywords."""
    descriptions = {
        "KEYWORD": "Model initialization",
        "NODE": "Node definitions",
        "ELEMENT_SHELL": "Shell element definitions",
        "ELEMENT_SOLID": "Solid element definitions",
        "ELEMENT_BEAM": "Beam element definitions",
        "ELEMENT_BEAM_ORIENTATION": "Beam elements with orientation vectors",
        "ELEMENT_MASS": "Mass element definitions",
        "ELEMENT_MASS_NODE_SET": "Mass elements on node sets",
        "ELEMENT_SHELL_THICKNESS": "Shell elements with variable thickness at each node",
        "ELEMENT_SEATBELT_ACCELEROMETER": "Seatbelt accelerometer element for occupant safety",
        "PART": "Standard part definitions",
        "PART_COMPOSITE": "Composite material parts",
        "PART_CONTACT": "Contact surface parts",
        "SECTION_SHELL_TITLE": "Shell section properties",
        "SECTION_SOLID_TITLE": "Solid section properties",
        "SECTION_BEAM_TITLE": "Beam section properties",
        "MAT_PIECEWISE_LINEAR_PLASTICITY_TITLE": "Piecewise linear plasticity material",
        "MAT_SPOTWELD_TITLE": "Spotweld material model",
        "MAT_SPOTWELD_DAMAGE": "Spotweld material with damage",
        "MAT_NONLINEAR_PLASTIC_DISCRETE_BEAM_TITLE": "Nonlinear plastic discrete beam material",
        "CONTACT_TIED_SHELL_EDGE_TO_SURFACE_BEAM_OFFSET_ID_MPP": "Tied contact between shell edge and surface",
        "CONTACT_TIED_SHELL_EDGE_TO_SURFACE_ID_CONSTRAINED_OFFSET_MPP": "Tied contact with constrained offset for shell-to-surface bonding (MPP)",
        "CONTACT_FORCE_TRANSDUCER_PENALTY_ID": "Force transducer contact for measuring interface forces",
        "CONSTRAINED_JOINT_REVOLUTE_ID": "Revolute joint constraints",
        "CONSTRAINED_NODAL_RIGID_BODY": "Nodal rigid body constraints",
        "CONSTRAINED_INTERPOLATION_SPOTWELD": "Spotweld interpolation constraint (mesh-independent)",
        "SET_NODE_LIST": "Node set definitions (list)",
        "SET_NODE_LIST_TITLE": "Node set definitions with title",
        "SET_NODE_TITLE": "Node set definitions",
        "SET_PART_LIST_TITLE": "Part set definitions",
        "SET_PART_COLLECT_TITLE": "Part collection sets",
        "SET_PART_LIST_COLLECT_TITLE": "Part list collection sets",
        "SET_SHELL_LIST_TITLE": "Shell element sets (list)",
        "SET_SHELL_TITLE": "Shell element sets",
        "SET_BEAM_COLLECT_TITLE": "Beam element collection sets",
        "SET_BEAM_GENERAL_TITLE": "General beam element sets",
        "SET_SOLID_COLLECT_TITLE": "Solid element collection sets",
        "DEFINE_CURVE_TITLE": "Load curve definitions",
        "DATABASE_HISTORY_BEAM": "Beam history output",
        "DATABASE_HISTORY_NODE": "Node history output for time-history post-processing",
        "DATABASE_CROSS_SECTION_PLANE_ID": "Cross-section force output on a defined plane",
        "DAMPING_PART_STIFFNESS": "Stiffness-proportional damping for specific parts",
        "INITIAL_AXIAL_FORCE_BEAM": "Initial axial force in beam elements (e.g. bolt preload)",
        "INITIAL_STRESS_SHELL": "Initial stress state in shell elements (e.g. residual stress from forming)",
    }
    return descriptions.get(keyword, "User-defined keyword")
